"""Command line entry point.

    python -m kanon twin build data/health-insurance
    python -m kanon gate run  data/health-insurance --agent good  --save runs/green.json
    python -m kanon gate run  data/health-insurance --agent broken --baseline runs/green.json

argparse, not typer: a handful of flags does not need a dependency.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml
from pydantic import ValidationError

from kanon.compile import check_fidelity, compile_spec, infer_transitions, load_traces
from kanon.domain import Domain
from kanon.gate.ci import evaluate, markdown
from kanon.gate.metrics import RunReport
from kanon.gate.runner import run_all
from kanon.twin import Pack, Twin


def build(directory: Path) -> int:
    """Validate a domain's behavior pack and describe the twin it produces."""
    try:
        domain = Domain.load(directory)
    except (ValidationError, ValueError, OSError) as exc:
        print(f"{directory}: invalid domain\n{exc}", file=sys.stderr)
        return 1

    twin = Twin(domain.pack)
    print(domain.name)
    for name, resource in domain.pack.resources.items():
        states = ", ".join(sorted(resource.states)) if resource.states else "-"
        seeded = len(twin.state().get(name, {}))
        print(f"  {name:<10} {seeded} seeded   {resource.state_field or 'stateless'}: {states}")

    operations = sorted(domain.pack.routes)
    print(f"  {len(operations)} operations: {', '.join(operations)}")
    # No coverage figure yet, on purpose: coverage means "of the spec's
    # operations", and the spec only enters the picture with the compiler.
    # A percentage we cannot compute honestly is worse than no percentage.
    print("pack ok")
    return 0


def _write_layer(path: Path, body: dict, kind: str) -> None:
    headers = {
        "generated": "# GENERATED by `kanon twin compile` from the spec. Do not hand-edit.\n",
        "inferred": "# INFERRED by an LLM -- REVIEW THIS. Delete the file to reject every guess.\n",
    }
    note = (
        "# Corrections go in pack.yaml, which is merged over this file and always\n"
        "# wins, so re-running the compiler cannot eat your edits.\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(headers[kind] + note + yaml.safe_dump(body, sort_keys=False), encoding="utf-8")


def compile_(
    spec_path: Path,
    out: Path | None,
    tools: str | None,
    infer: bool = False,
    traces_path: Path | None = None,
) -> int:
    """Compile an OpenAPI spec into a behavior pack.

    The spec pass is deterministic. `--infer` adds the LLM's transition guesses as
    a separate, clearly-labelled layer. `--traces` replays recorded calls through
    the result and exits non-zero if the twin disagrees with the real API.
    """
    try:
        raw = json.loads(spec_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"{spec_path}: cannot read spec\n{exc}", file=sys.stderr)
        return 1

    try:
        compiled = compile_spec(raw, tools=tools.split(",") if tools else None)
    except (ValidationError, ValueError) as exc:
        print(f"{spec_path}: cannot compile\n{exc}", file=sys.stderr)
        return 1

    print(f"{compiled.pack.name}: {compiled.coverage} operations expressible")
    for resource, definition in sorted(compiled.pack.resources.items()):
        state = f", state: {definition.state_field}" if definition.state_field else ""
        print(f"  {resource:<14} {len(definition.fields)} fields{state}")

    if compiled.uncovered:
        print(f"\n  {len(compiled.uncovered)} operations NOT covered -- flagged, never faked:")
        for gap in compiled.uncovered:
            print(f"    {gap.method.upper():<6} {gap.path}  ({gap.reason})")

    print("\n  review before trusting this twin:")
    for note in compiled.notes:
        print(f"    - {note}")

    if out:
        _write_layer(
            out, compiled.pack.model_dump(exclude_defaults=True, exclude_none=True), "generated"
        )
        print(f"\nwrote {out}")

    if infer:
        if not compiled.states:
            print("\nnothing to infer: no resource has a status enum in the spec")
        else:
            inference = infer_transitions(compiled.pack, compiled.states)
            print(
                f"\ninferred transitions for {inference.resources} ({inference.model_calls} calls)"
            )
            for note in inference.rejected:
                print(f"    rejected: {note}")
            if inference.patch and out:
                inferred_path = out.with_name("pack.inferred.yaml")
                _write_layer(inferred_path, inference.patch, "inferred")
                print(f"wrote {inferred_path}  -- REVIEW: these are guesses, not spec")

    if traces_path:
        traces = load_traces(traces_path)
        layers = [out, out.with_name("pack.inferred.yaml")] if out else []
        pack = Pack.from_layers(*layers) if layers else compiled.pack
        fidelity = check_fidelity(pack, traces)
        print(f"\nfidelity: {fidelity.summary()}")
        for mismatch in fidelity.mismatches:
            print(f"    {mismatch.describe()}")
        if not fidelity.ok:
            return 1
    return 0


def run(
    directory: Path,
    agent_name: str,
    trials: int,
    baseline: Path | None,
    save: Path | None,
    k: int | None,
    max_drop: float,
) -> int:
    """Run every story, score it, compare to a baseline, print the verdict."""
    try:
        domain = Domain.load(directory)
        agent = domain.agent(agent_name)
    except (ValidationError, ValueError, KeyError, OSError) as exc:
        print(f"{directory}: {exc}", file=sys.stderr)
        return 1

    if not domain.stories:
        print(f"{directory}: no stories.yaml, nothing to run", file=sys.stderr)
        return 1

    twin = Twin(domain.pack)
    results = run_all(twin, domain.stories, agent, trials=trials)
    report = RunReport.from_results(
        domain.name,
        agent_name,
        results,
        twin.uncovered,
        model_calls=getattr(agent, "calls_made", 0),
    )

    k = k or report.trials
    previous = RunReport.load(baseline) if baseline else None

    print(markdown(report, previous, k, max_drop))

    if save:
        print(f"\nsaved {report.save(save)}", file=sys.stderr)

    verdict, _ = evaluate(report, previous, k, max_drop)
    return verdict.exit_code


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="kanon")
    groups = parser.add_subparsers(dest="group", required=True)

    twin_commands = groups.add_parser("twin", help="the deterministic twin").add_subparsers(
        dest="command", required=True
    )
    build_cmd = twin_commands.add_parser("build", help="validate a domain and describe its twin")
    build_cmd.add_argument("domain", type=Path)

    compile_cmd = twin_commands.add_parser(
        "compile", help="compile an OpenAPI spec into a behavior pack"
    )
    compile_cmd.add_argument("spec", type=Path)
    compile_cmd.add_argument(
        "-o", "--out", type=Path, default=None, help="write pack.generated.yaml"
    )
    compile_cmd.add_argument(
        "--tools",
        default=None,
        help="comma-separated operationIds the agent uses; omit to compile every operation",
    )
    compile_cmd.add_argument(
        "--infer",
        action="store_true",
        help="ask an LLM for state transitions; written to a separate pack.inferred.yaml",
    )
    compile_cmd.add_argument(
        "--traces",
        type=Path,
        default=None,
        help="recorded call sequences to replay; exits 1 if the twin disagrees",
    )

    gate_commands = groups.add_parser("gate", help="the scoring gate").add_subparsers(
        dest="command", required=True
    )
    run_cmd = gate_commands.add_parser("run", help="run every story and print a verdict")
    run_cmd.add_argument("domain", type=Path)
    run_cmd.add_argument("--agent", required=True, help="which agent in the domain's agents.py")
    run_cmd.add_argument("--trials", type=int, default=1, help="attempts per story")
    run_cmd.add_argument("-k", type=int, default=None, help="pass^k k (default: --trials)")
    run_cmd.add_argument("--baseline", type=Path, default=None, help="a saved report to compare to")
    run_cmd.add_argument("--save", type=Path, default=None, help="where to write this report")
    run_cmd.add_argument(
        "--max-drop", type=float, default=0.0, help="pass^k a slice may lose without failing"
    )

    args = parser.parse_args(argv)
    if args.group == "twin":
        if args.command == "compile":
            return compile_(args.spec, args.out, args.tools, args.infer, args.traces)
        return build(args.domain)
    return run(
        args.domain, args.agent, args.trials, args.baseline, args.save, args.k, args.max_drop
    )


if __name__ == "__main__":
    raise SystemExit(main())
